trigger:
- main

pool:
  name: Default

stages:
- stage: TerraformInit
  jobs:
  - job: Init
    steps:
    - pwsh: terraform init
      displayName: Terraform Init

- stage: TerraformPlan
  jobs:
  - job: Plan
    steps:
    - pwsh: terraform plan
<<<<<<< HEAD
      displayName: Terraform Plan
=======
      displayName: Terraform Plan
>>>>>>> 4e3045efbf7543cba5575ca93f98840de2f97991
